### ISSUE TITLE
Increase coverage of the binary expression matching

### ISSUE THREAD

**Issue by marcelo-sousa-sonarsource** [SonarSource/slang#16]

**Comment by marcelo-sousa-sonarsource** [comment]
11:31:47.664 ERROR: Error during SonarQube Scanner execution                                                                                                                                                                                                                                                                                       
java.lang.IllegalStateException: Binary operation type not supported: ELVIS                                                                                                                                                                                                                                                                        
        at com.sonarsource.slang.kotlin.KotlinTreeVisitor.mapBinaryExpression(KotlinTreeVisitor.java:116)                                                                                                                                                                                                                                          
        at com.sonarsource.slang.kotlin.KotlinTreeVisitor.createElement(KotlinTreeVisitor.java:101)                                                                                                                                                                                                                                                
        at com.sonarsource.slang.kotlin.KotlinTreeVisitor.visitElement(KotlinTreeVisitor.java:88)                                                                                                                                                                                                                                                  
        at org.jetbrains.kotlin.psi.KtVisitor.visitKtElement(KtVisitor.java:24)

**Comment by marcelo-sousa-sonarsource** [comment]
11:33:37.531 ERROR: Error during SonarQube Scanner execution                                                                                                                                                                                                                                                                                       
java.lang.IllegalStateException: Binary operation type not supported: EXCLEQEQEQ                                                                                                                                                                                                                                                                   
        at com.sonarsource.slang.kotlin.KotlinTreeVisitor.mapBinaryExpression(KotlinTreeVisitor.java:116)                                                                                                                                                                                                                                          
        at com.sonarsource.slang.kotlin.KotlinTreeVisitor.createElement(KotlinTreeVisitor.java:101)                                                                                                                                                                                                                                                
        at com.sonarsource.slang.kotlin.KotlinTreeVisitor.visitElement(KotlinTreeVisitor.java:88)                                                                                                                                                                                                                                                  
        at org.jetbrains.kotlin.psi.KtVisitor.visitKtElement(KtVisitor.java:24)
